stripe/pg-schema-diff

README.md, internal/migration_acceptance_tests/acceptance_test.go, internal/migration_acceptance_tests/check_constraint_cases_test.go, internal/migration_acceptance_tests/column_cases_test.go, internal/migration_acceptance_tests/function_cases_test.go, internal/migration_acceptance_tests/index_cases_test.go, internal/migration_acceptance_tests/local_partition_index_cases_test.go, internal/migration_acceptance_tests/partitioned_index_cases_test.go, internal/migration_acceptance_tests/partitioned_table_cases_test.go, internal/migration_acceptance_tests/schema_cases_test.go, internal/migration_acceptance_tests/sequence_cases_test.go, internal/migration_acceptance_tests/table_cases_test.go, internal/migration_acceptance_tests/trigger_cases_test.go, internal/queries/queries.sql, internal/queries/queries.sql.go, internal/schema/schema.go, internal/schema/schema_test.go, pkg/diff/diff.go, pkg/diff/plan_generator.go, pkg/diff/sql_generator.go, pkg/schema/schema_test.go
Add sequence (and serial support). A little gross because we all columns ops are grouped in the same add/alter block.
https://github.com/stripe/pg-schema-diff/issues/34
Tested via acceptance tests
=> Add sequence support

pkg/diff/schema_migration_plan_test.go, pkg/diff/sql_generator.go
Noticed that there's a space missing between a create table statement and its partition by clause. This was not an issue before because postgres considers the word after a closing paren to be a new token, even if there's no space. This fix is purely stylistic
```
CREATE TABLE(...)PARTITION BY ... -> CREATE TABLE(...) PARTITION BY ...
^
|
```
Saw this while generating a plan
Added a plan unit test covering a raw table create with partition.
Before:
```
alexaub in ~/stripe/pg-schema-diff on alexaub/partition-whitespace ● λ …
```
=> Fix whitespace in  PARTITION BY clause 

.github/workflows/run-tests.yaml
Makes it a bit clearer in views what the different run_tests jobs are by including postgresql in the version. Feel free to push back if you think this harms brevity.
Old:
New:
Didn't know what run_tests (14) and run_tests (15) were in a PR
CI
=> Show postgres in run_tests job name

.github/workflows/lint.yaml, .sqlfluff, CONTRIBUTING.md, Makefile, build/Dockerfile.lint, cmd/pg-schema-diff/cli.go, internal/queries/queries.sql, internal/queries/queries.sql.go, internal/schema/schema.go
Uses SQLfluff for linting. This linter requires folks to have python installed or use docker. There aren't any super great-looking go SQL linters, and most folks have Python installed on their machines, so it should be fine.
Enforce a consistent style in SQL
Tested locally and in CI
=> SQL linting

README.md, internal/migration_acceptance_tests/acceptance_test.go, internal/migration_acceptance_tests/check_constraint_cases_test.go, internal/migration_acceptance_tests/column_cases_test.go, internal/migration_acceptance_tests/foreign_key_constraint_cases_test.go, internal/migration_acceptance_tests/partitioned_table_cases_test.go, internal/migration_acceptance_tests/schema_cases_test.go, internal/migration_acceptance_tests/sequence_cases_test.go, internal/migration_acceptance_tests/table_cases_test.go, internal/queries/queries.sql, internal/queries/queries.sql.go, internal/schema/schema.go, internal/schema/schema_test.go, pkg/diff/plan.go, pkg/diff/schema_migration_plan_test.go, pkg/diff/sql_generator.go, pkg/schema/schema_test.go
Add foreign key support
https://github.com/stripe/pg-schema-diff/issues/49
Tested with acceptance tests
=> Add foreign key support

cmd/pg-schema-diff/apply_cmd.go, cmd/pg-schema-diff/flags.go, cmd/pg-schema-diff/plan_cmd.go, pkg/log/logger.go
`psql` and programs using `libpq` allows users to use the environment variables `PGHOST` and friends to specify the connection information. This PR implements the same behavior for `pg-schema-diff` by making the DSN flag non-mandatory.
- We already set the Postgres environment variables in our development and deployment environments.
- The Javascript and Golang libraries we use honor the variables.
- This change makes `pg-schema-diff` "just work" in our workflow.
-  pg-schema-diff's `(connFlags).parseConnConfig()` calls  `pgx.ParseConfig()`, which calls `pgconn.ParseConfigWithOptions()`
- `pgconn.ParseConfigWithOptions` already reads the Postgres environment variables.
- I've tested the change manually on the command line and it works as expected
=> cmd: make dsn a non-mandatory flag to allow use of Postgres environment variables

internal/pgengine/engine.go
Before, if `PGUSER` was set on a user's machine, local tests would break because we didn't specify user. Now, the user is specified in the pgengine. This also switches the super user from the current user to `postgres`
Improved UX when running tests
Unit tests
=> Specify user in pgengine

README.md
This is fixing a word.
The incorrectly capitalized character was an eyesore in the readme, which is the first place users go to when viewing this repo.
I have read the changed line like 20 times.
=> fixed buggy english

internal/migration_acceptance_tests/partitioned_index_cases_test.go, internal/queries/queries.sql, internal/queries/queries.sql.go, internal/schema/schema.go, internal/schema/schema_test.go, pkg/diff/schema_migration_plan_test.go, pkg/diff/sql_generator.go, pkg/schema/schema_test.go
Build PK constraints concurrently for partitions. This will nicely transition into adding unique constraint support and building unique constraints concurrently for partitions.
#64 
Tested via acceptance tests
=> Building PK's Concurrently for Partitions

README.md, internal/migration_acceptance_tests/check_constraint_cases_test.go, pkg/diff/schema_migration_plan_test.go, pkg/diff/sql_generator.go
This was a pretty low-hanging fruit. We now add all check constraints as invalid and then validate them. This allows us to build check constraints "online".
Closes #66
Tested with unit tests
=> Online check constraint addition

README.md, go.mod, internal/graph/graph.go, internal/migration_acceptance_tests/acceptance_test.go, internal/migration_acceptance_tests/check_constraint_cases_test.go, internal/migration_acceptance_tests/column_cases_test.go, internal/migration_acceptance_tests/index_cases_test.go, internal/migration_acceptance_tests/local_partition_index_cases_test.go, internal/migration_acceptance_tests/partitioned_index_cases_test.go, internal/migration_acceptance_tests/table_cases_test.go, internal/queries/queries.sql, internal/queries/queries.sql.go, internal/schema/schema.go, internal/schema/schema_test.go, pkg/diff/diff.go, pkg/diff/schema_migration_plan_test.go, pkg/diff/sql_generator.go, pkg/diff/sql_generator_test.go, pkg/schema/schema_test.go, pkg/tempdb/factory.go
Use check constraints to make `SET NOT NULL` constraints online
One exception: This does not yet work for partitioned tables, since we don't yet support local check constraints
https://github.com/stripe/pg-schema-diff/issues/82
Tested via unit tests
=> Online not null constraints: `SET NOT NULL`

README.md, internal/migration_acceptance_tests/partitioned_index_cases_test.go, pkg/diff/sql_generator.go
Remove extraneous `NOT NULL` statement generation. If the parent table column is being altered from `NULL` -> `NOT NULL` (or vice versa), then we don't need to generate any SQL for the child table
Simplify SQL generation. This also removes false positive ACCESS_EXCLUSIVE_LOCK migration hazards
https://github.com/stripe/pg-schema-diff/issues/88
Acceptance tests
=> Remove extraneous `NOT NULL` statement generation. Update README

README.md, cmd/pg-schema-diff/plan_cmd.go, internal/migration_acceptance_tests/acceptance_test.go, pkg/diff/plan_generator.go, pkg/diff/plan_generator_test.go
Switch to interfaces that accept conn pools. I would have just switched it directly to conn pools, but that limits backwards compatibility. In a major version update, I might get rid of the interface and just use conn pools.
In a subsequent PR, we will parallelize schema fetching.
Passes acceptance tests.
CLI:
```
go run ./cmd/pg-schema-diff apply  --dsn "host=localhost user=postgres password=postgres database=somedb" --schema-dir …
```
=> Switch interfaces to accept conn pools

cmd/pg-schema-diff/plan_cmd.go, pkg/diff/plan_generator.go
Now that we fetch schemas in parallel, we should set a maximum number of connections on the connection pool for planning.
Follow best practices
```
go run ./cmd/pg-schema-diff apply  --dsn "host=localhost user=postgres password=postgres database=somedb" --schema-dir ~/stripe/temp/examplesql
################################## Review plan ##################################
1. ALTER TABLE "public"."foobar" DROP CONSTRAINT …
```
=> Set max connections for plan cmd

internal/migration_acceptance_tests/schema_cases_test.go, internal/queries/queries.sql, internal/queries/queries.sql.go, internal/schema/filters.go, internal/schema/filters_test.go, internal/schema/schema.go, internal/schema/schema_test.go, pkg/diff/plan_generator.go, pkg/diff/schema_migration_plan_test.go, pkg/schema/schema.go, pkg/schema/schema_test.go
This only adds support for fetching non-public schemas. This does actually allow generating migration plans for non-public schemas because we will need plumb several into the sql generation code to account for schemas.
I opted to do the filtering in-memory because it is way more flexible to do the filtering in-memory rather than in the queries. We can easily support things like regex and complex nested operations in the future (unions of intersections, etc). I don't expect the filters to significantly reduce the number of schema objects being fetched, …
=> Add support for fetching non-public schemas.

internal/migration_acceptance_tests/acceptance_test.go, internal/schema/filters.go, internal/schema/filters_test.go, internal/schema/schema.go, internal/schema/schema_test.go, pkg/diff/plan_generator.go, pkg/diff/schema_source.go, pkg/schema/schema.go, pkg/schema/schema_test.go, pkg/tempdb/factory.go, pkg/tempdb/factory_test.go
When using temp db factories (which have metadata tables), we need to tell the schema fetcher to ignore those tables.
This also technically switches acceptance tests to fetch non-public schemas; however, none of our tests actually have non-public schemas. 
The final step for supporting non-public schemas at this point is validating everything is actually working through the acceptance tests, updating the documentation, and removing the gate. …
=> Add exclude schemas

cmd/pg-schema-diff/apply_cmd.go, cmd/pg-schema-diff/flags.go, cmd/pg-schema-diff/plan_cmd.go, pkg/diff/plan_generator.go, pkg/diff/plan_generator_test.go
- Add multi-schema support to CLI
- Add support for a database schema source to the CLI
In a follow-up PR, I'm going to update the statement modifiers to follow logfmt. The current way they are specified is awful.
https://github.com/stripe/pg-schema-diff/issues/105
Normal (notice the some_schema related operations):
```
~/stripe/pg-schema-diff │ bplunkett/up…hema-support  go run ./cmd/pg-schema-diff plan  --dsn "host=localhost …
```
=> Update CLI with multi-schema support and database schema source

cmd/pg-schema-diff/datastructs.go, cmd/pg-schema-diff/datastructs_test.go, cmd/pg-schema-diff/flags.go, cmd/pg-schema-diff/flags_test.go, cmd/pg-schema-diff/plan_cmd.go, cmd/pg-schema-diff/plan_cmd_test.go, go.mod, go.sum
- Switch to logfmt parameters. This is @alexaub-stripe's great idea!
- Add support for lock timeout modifiers
Fixed #62 
```
~/stripe/pg-schema-diff │ bplunkett/ov…an-modifiers  go run ./cmd/pg-schema-diff plan  --dsn "host=localhost user=postgres password=postgres database=somedb" --schema-dir ~/stripe/temp/examplesql -s 'index=1 timeout=2h lock_timeout=3m statement="SOME INSERTED STATEMENT"' --exclude-schema=public …
```
=> Use logfmt for plan modifiers

internal/migration_acceptance_tests/sequence_cases_test.go, pkg/diff/sql_generator.go
Add support for altering sequences
Fixes #110 
Tested with unit tests
=> Add support for altering sequences

cmd/pg-schema-diff/plan_cmd.go
Make data-packing toggle-table. It is on by default. To disable, pass the option: `-data-pack-new-tables=false`
https://github.com/stripe/pg-schema-diff/issues/118
```
go run ./cmd/pg-schema-diff plan  --dsn "host=localhost user=postgres password=postgres database=somedb" --schema-dir ~/stripe/temp/examplesql
################################ Generated plan ################################
1. CREATE TABLE "public"."foobar" (
"id" integer, …
```
=> Make data-packing toggle-able

internal/migration_acceptance_tests/enum_cases_test.go, internal/migration_acceptance_tests/schema_cases_test.go, internal/queries/queries.sql, internal/queries/queries.sql.go, internal/schema/schema.go, internal/schema/schema_test.go, internal/set/set.go, internal/set/set_test.go, pkg/diff/enum_sql_generator.go, pkg/diff/sql_generator.go
Add enum support
Fixes #112 
@sweatybridge
Tested via unit tests
=> Add enum support

internal/queries/queries.sql, internal/queries/queries.sql.go
Exclude schemas owned by extensions.
pg_repack creates a schema called pg_repack. Let's say the user's `model.sql` removes the `CREATE EXTENSION pg_repack` line. This will generate two statements:
1. Drop extension pg_repack
2. Drop schema pg_repack
The first line drops the pg_repack schema as well because it is owned by the extension, causing the second line to fail. As a result, we should stop generating statements for schemas owned by extensions, just like we do with other schema objects.
[//]: # (Why you made these changes. Link to any relevant …
=> Exclude schemas owned by extensions

cmd/pg-schema-diff/plan_cmd.go
Optionally disable plan validation for CLI
https://github.com/stripe/pg-schema-diff/issues/129
Just showing the flag is parsed correctly:
```
go run ./cmd/pg-schema-diff plan  --dsn "host=localhost database=postgres" --schema-dir ~/stripe/temp/examplesql  --disable-plan-validation --disable-plan-validation
################################ Generated plan ################################
01. CREATE SCHEMA "some_new_schema";
-- Statement …
```
=> [CLI] Add flag to disable plan validation

internal/migration_acceptance_tests/acceptance_test.go, internal/migration_acceptance_tests/backwards_compat_cases_test.go, internal/migration_acceptance_tests/check_constraint_cases_test.go, internal/migration_acceptance_tests/column_cases_test.go, internal/migration_acceptance_tests/enum_cases_test.go, internal/migration_acceptance_tests/extensions_cases_test.go, internal/migration_acceptance_tests/function_cases_test.go, internal/migration_acceptance_tests/index_cases_test.go, internal/migration_acceptance_tests/local_partition_index_cases_test.go, internal/migration_acceptance_tests/named_schema_cases_test.go, internal/migration_acceptance_tests/partitioned_index_cases_test.go, internal/migration_acceptance_tests/partitioned_table_cases_test.go, internal/migration_acceptance_tests/policy_cases_test.go, internal/migration_acceptance_tests/schema_cases_test.go, internal/migration_acceptance_tests/sequence_cases_test.go, internal/migration_acceptance_tests/table_cases_test.go, internal/migration_acceptance_tests/trigger_cases_test.go, internal/pgengine/actions.go, internal/pgengine/db.go, internal/queries/queries.sql, internal/queries/queries.sql.go, internal/schema/schema.go, internal/schema/schema_test.go, pkg/diff/diff.go, pkg/diff/plan.go, pkg/diff/plan_generator.go, pkg/diff/policy_sql_generator.go, pkg/diff/sql_generator.go
- Add support for RLS Policies
- RLS policies cannot be added to individual partitions yet, but they can be put on the parent table (I want to refactor the code a bit)
Little status update: Bit of a hiatus due to other priorities. Before adding more features to schema diffing, I'd like to clean up the tests and code a bit.
cc @sweatybridge
Fixes #111 
Tested via unit tests
=> RLS Policies

internal/migration_acceptance_tests/acceptance_test.go, internal/migration_acceptance_tests/backwards_compat_cases_test.go, internal/migration_acceptance_tests/check_constraint_cases_test.go, internal/migration_acceptance_tests/column_cases_test.go, internal/migration_acceptance_tests/data_packing_cases_test.go, internal/migration_acceptance_tests/enum_cases_test.go, internal/migration_acceptance_tests/extensions_cases_test.go, internal/migration_acceptance_tests/foreign_key_constraint_cases_test.go, internal/migration_acceptance_tests/function_cases_test.go, internal/migration_acceptance_tests/index_cases_test.go, internal/migration_acceptance_tests/local_partition_index_cases_test.go, internal/migration_acceptance_tests/named_schema_cases_test.go, internal/migration_acceptance_tests/partitioned_index_cases_test.go, internal/migration_acceptance_tests/partitioned_table_cases_test.go, internal/migration_acceptance_tests/policy_cases_test.go, internal/migration_acceptance_tests/schema_cases_test.go, internal/migration_acceptance_tests/table_cases_test.go, internal/migration_acceptance_tests/trigger_cases_test.go
- Instead of each test case defining two specs for vanilla and data packing, run data packing as their own independent test cases. This simplifies test specs and running tess
- Flatten `expectations`. The distinction was arbitrary because of the need to potentially define two test specs
The fact that this is net negative code despite copying two test cases -- we really only had TWO data packing test cases for all of this complexity in the test spec -- implies this PR moves the code in the right direction.
[//]: # (Why you made these changes. Link to …
=> Update Acceptance Tests - Flatten specs

build/Dockerfile.test
It seems postgresql-contrib installs postgresql16, which then had precedence in the $PATH. This resulted in the tests running postgresql16 for the non-16 tests. Obviously, this is not the behavior we want. I validated this because in the [postgresql 14 logs](https://productionresultssa8.blob.core.windows.net/actions-results/6fad0e39-9e29-4eb3-bc5f-7ff4eb01baa2/workflow-job-run-d0ba29aa-214f-539c-d02c-c4463caefb4e/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-07-03T22%3A42%3A42Z&sig=%2F1Y7gF6Vuoiye1B9PV5qGOni4oK2qQorCfxkc5KdFSc%3D&ske=2024-07-04T06%3A4 …
=> Use the test environment that is intended to be used

CONTRIBUTING.md, internal/migration_acceptance_tests/acceptance_test.go, internal/migration_acceptance_tests/backwards_compat_cases_test.go, internal/migration_acceptance_tests/check_constraint_cases_test.go, internal/migration_acceptance_tests/column_cases_test.go, internal/migration_acceptance_tests/data_packing_cases_test.go, internal/migration_acceptance_tests/database_schema_source_cases_test.go, internal/migration_acceptance_tests/enum_cases_test.go, internal/migration_acceptance_tests/extensions_cases_test.go, internal/migration_acceptance_tests/foreign_key_constraint_cases_test.go, internal/migration_acceptance_tests/function_cases_test.go, internal/migration_acceptance_tests/index_cases_test.go, internal/migration_acceptance_tests/local_partition_index_cases_test.go, internal/migration_acceptance_tests/named_schema_cases_test.go, internal/migration_acceptance_tests/partitioned_index_cases_test.go, internal/migration_acceptance_tests/partitioned_table_cases_test.go, internal/migration_acceptance_tests/policy_cases_test.go, internal/migration_acceptance_tests/schema_cases_test.go, internal/migration_acceptance_tests/sequence_cases_test.go, internal/migration_acceptance_tests/table_cases_test.go, internal/migration_acceptance_tests/trigger_cases_test.go
Standardizing the whitespace in the migration_acceptance_tests to be spaces so viewing isn't uneven.
Resolves #67 
I ran the test docker image built on my local machine and observed no test failures which is expected given the only changes are whitespace. The one caveat is it was only run against `postgres` 14 given that was the specified arg in the test dockerfile.
=> fix: #67 converting all tabs to spaces in migration acceptance tests

README.md, internal/migration_acceptance_tests/backwards_compat_cases_test.go, internal/migration_acceptance_tests/database_schema_source_cases_test.go, internal/migration_acceptance_tests/foreign_key_constraint_cases_test.go, internal/migration_acceptance_tests/schema_cases_test.go, internal/migration_acceptance_tests/table_cases_test.go, pkg/diff/sql_generator.go
Online foreign key support via `VALIDATE`. 
Unfortunately, it is not possible to add `NOT VALID` constraints to partitioned tables, so this strategy can only work when adding foreign keys to normal tables. It _does_ work on partitions, so if a user really wanted to add foreign key constraints safely on a partitioned table, they could just add n foreign key constraints, one per partition, rather than just 1.
Fixes #97 
Tested via acceptance …
=> Online foreign key support

internal/migration_acceptance_tests/index_cases_test.go, internal/migration_acceptance_tests/partitioned_index_cases_test.go
Adds test cases to cover [functional indexes](https://www.postgresql.org/docs/7.3/indexes-functional.html) to ensure that we test them in perpetuity.
A callout: under the hood the apply generates with a type cast for the input to the lower function (which only accepts text not varchar) which is different from the user provided definition without the cast. I think this doesn't trip up the tests and is desirable behavior because in reality pg-schema-diff is diffing schema that's been applied and read from a test database, not the user provided schema, so …
=> Add test cases for functional indexes

internal/queries/queries.sql, internal/queries/queries.sql.go, internal/schema/schema.go, internal/schema/schema_test.go, pkg/diff/sql_generator.go
Index columns effectively have two occurrences in pg_attribute, one is a "virtual column" created for the index and the other is the actual referenced column. For our purposes, we care about the latter, i.e., ensuring an index is deleted before its owning column is dropped, otherwise the index will be implicitly deleted (and not concurrently).
When a column is renamed, the virtual column name stays the same, but the underlying column name obviously changes. pg-schema-diff contained a bug where it referenced the _virtual_ column name. Effectively, a …
=> Fix column renames for indexes

cmd/pg-schema-diff/plan_cmd.go
Support multiple schema dirs
Fixes #149 
Multiple:
```
go run ./cmd/pg-schema-diff plan --schema-dir ~/stripe/temp/examplesql --dsn 'host=localhost user=bplunkett dbname=postgres' --schema-dir ~/stripe/temp/examplesql2
################################ Generated plan ################################
1. CREATE SCHEMA "some_new_schema";
-- Statement Timeout: 3s
2. CREATE TABLE "public"."examplesql2_foobar" (
"id" text COLLATE …
```
=> Support multiple sql dirs

cmd/pg-schema-diff/flags.go, cmd/pg-schema-diff/flags_test.go, cmd/pg-schema-diff/plan_cmd.go
Support nested directories, i.e., walk nested directories
Fixes #155 
Relates to #162 
Validated on schema dir with nested folders:
```
|-foobar.sql
|-last
|  |-nested
|  |  |-fk.sql
|-earlier_schema
|  |-enum.sql
```
Execution order should be lexical order of file paths.
```
go run ./cmd/pg-schema-diff plan --schema-dir ~/stripe/tempschema --dsn 'host=localhost user=bplunkett dbname=postgres'           INT х │ 00:37:34 …
```
=> Support nested directories

cmd/pg-schema-diff/plan_cmd.go, internal/migration_acceptance_tests/database_schema_source_cases_test.go, internal/migration_acceptance_tests/testdata/dirsrc_happy_path/schema_0/0/0.sql, internal/migration_acceptance_tests/testdata/dirsrc_happy_path/schema_0/1.sql, internal/migration_acceptance_tests/testdata/dirsrc_happy_path/schema_0/2/0/0.sql, internal/migration_acceptance_tests/testdata/dirsrc_happy_path/schema_1/0.sql, internal/migration_acceptance_tests/testdata/dirsrc_invalid_sql/schema_0/0.sql, internal/migration_acceptance_tests/testdata/dirsrc_invalid_sql/schema_0/1.sql, pkg/diff/schema_source.go
Improve schema source errors to include file path that errored. Including line number is not really viable right now because it would require splitting a string blob into individual SQL statements. Parsing SQL is pretty fragile, and it's something pg-schema-diff tries to avoid. We can revisit adding that functionality later.
cc @aleclarson
Partially fixes #167 
Error with file name:
```
go run ./cmd/pg-schema-diff plan --schema-dir …
```
=> Improve dir schema source errors

README.md, cmd/pg-schema-diff/main.go, cmd/pg-schema-diff/version_cmd.go
Create simple version command to help with debugging
None
It says "(devel)" beecause it is the version of the locally build command (which has no version). This code should print out the same info as `go version -m (binary path)`
New command:
```
go run ./cmd/pg-schema-diff version                                                                                                   INT х │ 01:01:02
version=(devel)
```
Example of go version of …
=> Create simple version command

cmd/pg-schema-diff/plan_cmd.go, pkg/diff/plan.go
This adds support for different output formats when running the `plan` subcommand. Currently it only supports pretty printing (which is what already exists today) or JSON.
I rarely/never write golang so this PR was more or less a first attempt to get a discussion going, happy to refactor as needed.
I'm working on a tool written in Python that is using the pg-schema-diff to generate schema plans. It would be great to have a structured output option so I can just parse the output in Python.
Alternatively I can build some kind of bindings for this library, that would require waaay more overhead than just being able to parse the JSON output.
I think this would make the tool much more versatile.
Just manual testing. I'm happy to add test coverage, but I didn't see any other CLI tests (besides …
=> Add JSON output support to pg-schema-diff plan.

internal/migration_acceptance_tests/procedure_cases_test.go, internal/migration_acceptance_tests/schema_cases_test.go, internal/queries/queries.sql, internal/queries/queries.sql.go, internal/schema/schema.go, internal/schema/schema_test.go, pkg/diff/function_sql_vertex_generator.go, pkg/diff/procedure_sql_vertex_generator.go, pkg/diff/sql_generator.go
Add support for procedures. This support is very --iffy-- because Postgres does not actually track procedure dependencies outside of at creation time. In other words, you can drop a procedure's dependencies without dropping the procedure.
Closes #159 
Tested via acceptance tests
=> [Feature] Add support for Procedures

.github/workflows/run-tests.yaml, .golangci.yaml, README.md, build/Dockerfile.lint, build/Dockerfile.test, internal/graph/graph.go, internal/graph/graph_test.go, internal/migration_acceptance_tests/sequence_cases_test.go, internal/queries/queries.sql, internal/queries/queries.sql.go, internal/schema/schema.go, internal/schema/schema_test.go, pkg/diff/sql_generator.go, pkg/diff/transform_diff.go
- Add support for postgres17. The newest version of alpine with postgres17 in its package repository does not have postgres14 in its repository, so our test image needs to be able to support multiple base docker images
- Fix typos as noted by the go report code
- Add gofmt to the linter...which adds code "simplification"...this manifested as the for-loop simplifications seen in this PR
Fixes #186
Testing via CI
=> Add support for Postgres17 (+ misc linting changes)

README.md, cmd/pg-schema-diff/plan_cmd.go, internal/migration_acceptance_tests/acceptance_test.go, internal/migration_acceptance_tests/database_schema_source_cases_test.go, pkg/diff/plan_generator.go, pkg/diff/plan_generator_test.go
This PR change the `Generate` function to take a `SchemaSource` instead of a `sqldb.Queryable`.
We're using this library to generate migrations and this option allows us to generate forward **and** backward migrations, based on the wanted schema and database.
The change allows for better flexibility in  `Generate` and let's us just swap arguments to the function, to generate both migrations at once.
Tests with the …
=> Change the Generate function to take a SchemaSource instead of a sqldb.Queryable

README.md, cmd/pg-schema-diff/apply_cmd.go, cmd/pg-schema-diff/apply_cmd_test.go, cmd/pg-schema-diff/flags.go, cmd/pg-schema-diff/main.go, cmd/pg-schema-diff/main_test.go, cmd/pg-schema-diff/plan_cmd.go, cmd/pg-schema-diff/plan_cmd_test.go, cmd/pg-schema-diff/version_cmd.go, internal/pgengine/engine.go, internal/util/closer.go, internal/util/closer_test.go
Changes:
- Allow users to generate plans FROM a schema directory
- Allow both the from and to databases to be schema directories IF the user provides a temporary database
- Switch commands to print through the `cobra.Command` proxy
- Spin out tests for the plan and apply commands. Testing these manually was getting too complex
https://github.com/stripe/pg-schema-diff/issues/198
Added tests for these core commands because it was getting too …
=> [FEATURE] Add support for `--from-dir` and providing a dedicated temporary database server

pkg/tempdb/factory.go
This PR add an option to set statement timeout for database drop of the tempdb.
When using pg-schema-diff on an azure managed database, the database drop statement take time (around 10s), generating error when using pg-schema-diff (and creating strange shadow databases).
With this, any suitable timeouts can be set depending on user context.
Tested locally in my context, 'issue' is fixed.
No unit test because it seems hard to test, but I'm open to suggestions.
=> Add custom timeout for tmpdb's database drops

cmd/pg-schema-diff/apply_cmd.go
Fixing a typo in the help text for `--allow-hazards`
=> Fix incorrect cmd name in help text

Makefile, scripts/acceptance_test_sql_linter/main.go
Adding a Go script that will do the whitespace tab to four spaces replacement for the acceptance test files.
Resolves issue #148 
I ran the script both from the root of the directory and via the Makefile commands and observed they ran as expected.
=> feat: #148 adding go script and makefile commands

build/Dockerfile.test, internal/migration_acceptance_tests/acceptance_test.go, internal/migration_acceptance_tests/backwards_compat_cases_test.go, internal/migration_acceptance_tests/check_constraint_cases_test.go, internal/migration_acceptance_tests/column_cases_test.go, internal/migration_acceptance_tests/data_packing_cases_test.go, internal/migration_acceptance_tests/database_schema_source_cases_test.go, internal/migration_acceptance_tests/enum_cases_test.go, internal/migration_acceptance_tests/extensions_cases_test.go, internal/migration_acceptance_tests/foreign_key_constraint_cases_test.go, internal/migration_acceptance_tests/function_cases_test.go, internal/migration_acceptance_tests/index_cases_test.go, internal/migration_acceptance_tests/local_partition_index_cases_test.go, internal/migration_acceptance_tests/named_schema_cases_test.go, internal/migration_acceptance_tests/partitioned_index_cases_test.go, internal/migration_acceptance_tests/partitioned_table_cases_test.go, internal/migration_acceptance_tests/policy_cases_test.go, internal/migration_acceptance_tests/procedure_cases_test.go, internal/migration_acceptance_tests/schema_cases_test.go, internal/migration_acceptance_tests/sequence_cases_test.go, internal/migration_acceptance_tests/table_cases_test.go, internal/migration_acceptance_tests/trigger_cases_test.go, internal/pgidentifier/identifier.go, pkg/diff/plan_generator.go, pkg/diff/schema_migration_plan_test.go, pkg/diff/sql_generator.go, pkg/tempdb/factory.go
Stop using a test suite in the acceptance tests. This enables us to leverage `t.Parallel`. Because tests ran in parallel, to maintain the same "randomly" generated outputs, I wired through a rand reader rather than relying on a global singleton. This makes tests about 50% faster
Before:
After:
Speed up acceptance tests.
[//]: # Describe how you tested these changes
Ran locally
=> Accelerate tests

README.md, internal/migration_acceptance_tests/materialized_view_cases_test.go, internal/queries/queries.sql, internal/queries/queries.sql.go, internal/schema/schema.go, internal/schema/schema_test.go, pkg/diff/materialized_view_sql_generator.go, pkg/diff/sql_generator.go
A very rough implementation of materialized view support. This does not add support for indexes on materialized views (yet)
https://github.com/stripe/pg-schema-diff/issues/173
Tested locally
=> Add materialized views MVP
